### ISSUE TITLE
Issue with application opening

### ISSUE THREAD

**Issue by MrPlugyMan** [MREdigital/Parrity#1]
Hey! I’m facing problem.
1. Can’t open app from iPhone 7 (ios 13.4), closes immediately app in a second as I open it.
2. Can’t accept EULA rules, because of nr. 1. point.
3. As I open app from Apple Watch 4 (ios 6.2), shows only text: Waiting for connection.
3.1. Can’t open any features what are displayed (search, url, earth icon).
3.2. Only thing what opens is after stronger/longer hold on screen, opens options page.

Will wait for your contact

**Comment by MrEdigital** [comment]
Hiya, Mr. Plugy Man,

I managed to reproduce this in such a way that I was able to narrow down the issue just recently.  The fix is currently in review with Apple and should hopefully go live some time in the next day or so.

Thanks for reaching out!  Sorry for the inconvenience!
Eric

**Comment by MrPlugyMan** [comment]
Hey!

Thank you for this fast feedback and informing about current solution.

I was in first though, that I might find you around Reddit, because that’s the source where I found out about this application.

After some days of waiting, I was a bit of dissapointed. But as I opened ticked here, you were fast by giving hopes and feedback up about current situation.

I copyed your feedback text and pasted in reddit. I hope you don’t mind it.

**Comment by MrEdigital** [comment]
Version 1.3.4 just went live yesterday.  Please let me know if you still experience any problems.

Thanks!
Eric

**Comment by MrPlugyMan** [comment]
Hey!

This problem was solved.

But now I have another problem, it doesnt show website in watch. It shows blank black screen, with buttons like in the beginning, when I open the app from watch. In phone app, everything works perfectly.

**Comment by MrEdigital** [comment]
Hm.  Try the following and see if it works:

1 - Try another site.
2 - Reboot both devices.
3 - When loading the page, try it with the iPhone app launched.
4 - Resnap after trying to load the page.  Does it produce anything different?
5 - Reinstall both apps and try again?
6 - If you still aren’t seeing anything, please provide device details (phone/watch device types and OS versions) and I’ll try to reproduce it myself.

Sorry you’re still having trouble.  Hopefully we can get it worked out.

**Comment by MrPlugyMan** [comment]
Hey!

Problem solved.
Helpful was both device restart and I also had to close all apps in backgound.

* Boot your phone first and then watch.

**Comment by MrEdigital** [comment]
Ah, great!  Hopefully it’ll work reliably for you from here on out.

Happy browsing!
Eric
